remote: true
hybrid: true
onsite: true

experience_level:
  internship: false
  entry: false
  associate: false
  mid_senior_level: true
  director: true
  executive: true

job_types:
  full_time: true
  contract: false
  part_time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all_time: false
  month: true
  week: true
  24_hours: true

positions:
  - Technical Product Manager
  - Product Manager
  - Technical Project Manager
  - Senior Product Manager

locations:
  - Italy
  - Spain
  - Portugal
  - Ireland
  - France

apply_once_at_company: false

distance: 100

company_blacklist:

title_blacklist:
  - Engineer

location_blacklist:
  - California
  - Washington
  - Seattle
  - Chicago
  - New York
  - United States of America
  - United States

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'
